### ISSUE TITLE
Select does not have an arrow

### ISSUE THREAD

**Issue by fracz** [mdbootstrap/mdb-ui-kit#1117]
Why select input has no arrow? It looks like text input at the first glance.

Screenshot from http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html:

![image](https://cloud.githubusercontent.com/assets/3918865/20116017/dc6b3f86-a5fa-11e6-93e1-4e23704bee24.png)

The following CSS fixes the problem at least for Chrome (i.e. overrides the styles from bootstrap material design):

```css
.form-group select {
  -webkit-appearance: menulist-button;
}
```

![image](https://cloud.githubusercontent.com/assets/3918865/20116150/7c75a98a-a5fb-11e6-84ec-0d540e65c1e4.png)
