### ISSUE TITLE
custom-forms partial causes any custom .btn selectors to break in Chrome 60 when compiling from SCSS

### ISSUE THREAD

**Issue by ArcanoxDragon** [mdbootstrap/mdb-ui-kit#1212]
#### Summary
Project is ASP.NET Core project, SCSS compiled to CSS using Gulp, tested on Windows 10 x64 in Chrome 60. Project SCSS files reference `bootstrap-material-design` SCSS files for colors, mixins, and several other conveniences.

Unfortunately, line 6 of `bootstrap-material-design/scss/_custom-forms.scss` causes any custom selectors containing `.btn` to be appended with `, .custom-file-control::before`, which, for some reason, causes Chrome to ignore such selectors.

For example, in another SCSS file, I defined the following as a test:

```scss
.btn .material-icons {
    border: 8px solid red !important;
}
```

This resulted in the following being outputted to my `main.css` file:

```css
.btn .material-icons, .custom-file-control::before .material-icons {
    border: 8px solid red !important;
}
```

Chrome did not apply a red border to any `.material-icons` elements. Commenting out all of `_custom-forms.scss` and recompiling fixed the problem.

#### Expected result
When including `bootstrap-material-design` as a SCSS library, selectors defined in project SCSS files should not be modified by any `@extend` directives to a point where they are no longer obeyed by a browser.
