### ISSUE TITLE
Height of select is more than input

### ISSUE THREAD

**Issue by PromanSEW** [mdbootstrap/mdb-ui-kit#1276]
#### Test Case
https://codepen.io/PromanSEW/pen/goJazp

#### Summary
Firefox 58

When composing inputs in one line, I see that `<select>` field has different height

#### Expected result
Select must be the same height as input

**Comment by PromanSEW** [comment]
@FezVrasta I added note that this bug is suitable for Firefox at least.
As manual fix I added these rules:
```css
select.form-control {
  padding-bottom: 0.125rem;
}
select.form-control:not([size]):not([multiple]) {
  height: auto;
}
```
Second rule was added because of strange rule in your CSS:
```css
select.form-control:not([size]):not([multiple]), select.custom-file-control:not([size]):not([multiple]) {
  height: calc(2.4375rem + 2px);
}
```
