### ISSUE TITLE
Documented Primary Button Color Not Same As CSS file

### ISSUE THREAD

**Issue by Prophet32j** [mdbootstrap/mdb-ui-kit#1287]
https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.css has a different color than what is documented in https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/material-design/buttons/

I am not sure if this is an accident or not, but I was expecting the new primary color as it is more appealing than the green.

https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.css
```css
.btn.btn-raised.btn-primary {
  color: #fff;
  background-color: #009688;
  border-color: #009688;
}
```

https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/material-design/buttons/
```css
.btn.btn-raised.btn-primary {
  color: #fff;
  background-color: #3f51b5;
  border-color: #3f51b5;
}
```
