### ISSUE TITLE
Problem with the installation of the generator with Jhipster 4.14.1 and Java 8

### ISSUE THREAD

**Issue by DaMair** [mdbootstrap/mdb-ui-kit#1299]
#### Test Case
no code available as i cant even install it

#### Summary
When i try to use the generator on a fresh JHipster installation i get several Errors. I use jhipster 4.14.1, Java 8 and the latest versions of npm etc.
First one is that "navbar.html" is not found. After that i get the error "Unable to find src/main/webapp/scss/main.scss or missing required jhipster-needle. Style not added to JHipster app." At this point i am not able to fix the problems. Am i missing some installation which is not included/required in Jhipster itself?

#### Expected result
that i can install bootstrap material

**Comment by FezVrasta** [comment]
please provide a repository where I can run a command to reproduce the problem, I'm sure you don't expect me to spend hours to try to reproduce your very specific problem. I'll reopen the issue once you provided the repro.

**Comment by DaMair** [comment]
Hi, sure! i am sorry i am pretty new to git. I hope i did it correctly.
repository: https://github.com/DaMair/ease-test

**Comment by DaMair** [comment]
i should add that i generated a few files in order to solve some File not found errors. for example the "navbar.html" which was not present in my clean Jhipster generated project.

**Comment by mraible** [comment]
This is not a problem with this project, it's a problem with [generator-jhipster-bootstrap-material-design](https://github.com/moifort/generator-jhipster-bootstrap-material-design). The module has not been updated for JHipster 4 or 5. 

Here are the steps necessary to use this library with JHipster 5 and Sass:

1. Install bootstrap-material-design:

    ```
    npm install bootstrap-material-design@4.1.1
    ```

2. Remove all variables from `src/main/webapp/content/scss/_bootstrap-variables.scss`.
3. Comment out the import for Bootstrap in `src/main/webapp/content/scss/vendor.scss`:

    ```
    // Import Bootstrap source files from node_modules
    // @import '~bootstrap/scss/bootstrap';
    ```

4. Add the following to import bootstrap-material-design in `src/main/webapp/content/scss/vendor.scss`:

    ```scss
    // Import Bootstrap Material Design
    @import url('https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons');
    @import '~bootstrap-material-design/scss/bootstrap-material-design';
    ```

5. Remove the following styles from `global.scss`:

    ```scss
    /* Error highlight on input fields */
    .ng-valid[required],
    .ng-valid.required {
        border-left: 5px solid green;
    }

    .ng-invalid:not(form) {
        border-left: 5px solid red;
    }
    ```

6. Add the following overrides on the dropdown menus so they look good.

    ```scss
    .dropdown-menu .dropdown-item.active, .dropdown-menu .dropdown-item:active {
        color: #fff !important;
    }

    .dropdown-menu .dropdown-item {
        display: inline-block !important;
        padding: 0.5rem 1.5rem !important;
        min-height: 2rem !important;
    }
    ```

It'd be nice if the overrides weren't required in step 6. Here's a screenshot after these changes.

<img width="1333" alt="jhipster5-material-design" src="https://user-images.githubusercontent.com/17892/43689517-c3d40fca-98c9-11e8-816e-73a03234b10c.png">

Here's what it looks like without the overrides.

<img width="1333" alt="material-design-without-overrides" src="https://user-images.githubusercontent.com/17892/43689520-d15d0412-98c9-11e8-8f6f-f98b2559353c.png">

Note that this does not give you labels like [these examples](https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/bootstrap-components/forms/), which would be a cool addition.
