### ISSUE TITLE
Using @extend inside a ::before can result in invalid css

### ISSUE THREAD

**Issue by valendres** [mdbootstrap/mdb-ui-kit#1323]
#### Test Case
https://codepen.io/valendres/pen/NzqyqN

#### Summary
Using @extend inside a ::before or ::after pseudo selector can result in invalid css, causing styling to not be applied to target elements. This happens when attempting to apply styling to elements within a `.btn`

#### Expected result
To be able to apply css on specific elements within a `.btn`.

#### Additional Information
If we define the following rule, you would expect the button to be blue and the icon within the button to be red. However, this is not the case.
```scss
.btn {
  color: #00f;
}

.btn .material-icons {
  color: #f00;
}

// Problematic scss: scss\custom-forms.scss
.custom-file-control {
  &::before {
    @extend .btn;
  }
}
```

It results in the following css:
```css
.btn, .custom-file-control::before {
  color: blue;
}

.btn .material-icons, .custom-file-control::before .material-icons {
  color: red;
}
```
We end up with a class selector inside a pseudo before. This is invalid CSS, therefore the entire block is invalidated, including `.btn .material-icons`.

There is only 1 occurrence of this extend issue: bootstrap-material-design\scss\custom-forms.scss
