### ISSUE TITLE
Navbar z-index issue

### ISSUE THREAD

**Issue by nprail** [mdbootstrap/mdb-ui-kit#1353]
#### Test Case
https://codepen.io/nprail/pen/gExqqz

#### Summary

`.fixed-top` navbars appear visually below certain items in an `.active` state such as pagination, list group items, and button group items. 

#### Expected result
`.fixed-top` navbars should appear visually above everything. 

#### Additional Information
The `.navbar` `z-index` is being overrided by the following line of code. This is making it visually lower than the `.active` items. The default `.fixed-top` `z-index` is set [here](https://github.com/twbs/bootstrap/blob/master/scss/_variables.scss#L680) to `1030`.

```css
.navbar {
  z-index: 1; // required to make the shadow overlap the below content (need is visible in mobile drawer overlay)
}
```
[scss/_navbar.scss#L2](https://github.com/FezVrasta/bootstrap-material-design/blob/master/scss/_navbar.scss#L2)
