### ISSUE TITLE
Icons color classes are broken

### ISSUE THREAD

**Issue by pavel-voronin** [mdbootstrap/mdb-ui-kit#177]
Look at the http://fezvrasta.github.io/bootstrap-material-design/: all the icons are gray. They have class `icon-material-pink`:

![dev tools screenshot](http://take.ms/x2pGy)

But there are no `.icon-material-pink` class in the compiled version:

``` css
.mdi-material-pink,icon-material-pink {
    color: #e91e63
}
```

Please, fix it.
