### ISSUE TITLE
How do I change the input color

### ISSUE THREAD

**Issue by GradyD** [mdbootstrap/mdb-ui-kit#382]
If I am not using grunt/bower and am just using the dist version how do I change the colors for certain elements? The specific element I need to change is the color that is applied when clicking on an input/select/textarea. 

Do I need to install bower in order to change the color or can I do it with strait CSS?

**Comment by FezVrasta** [comment]
You may override css

**Comment by GradyD** [comment]
Will do thanks!

**Comment by Jayuda** [comment]
Hello Mr. @GradyD ,
can you give me example CSS to override color on input text ?
Thank you verry much

**Comment by FezVrasta** [comment]
``` less
.material-input:focus, .form-control:focus, .form-control.focus {
    background-image: linear-gradient(@input-success, @input-success), linear-gradient(@input-underline-color, @input-underline-color);
}
```
