### ISSUE TITLE
Font-family problem when using .mdi-material-xxxx classes

### ISSUE THREAD

**Issue by 255kb** [mdbootstrap/mdb-ui-kit#411]
Hi, 
If I understand well, `.mdi-material-xxxx / .icon-material-xxxx` classes allow to apply a specific color to some text/icon.
But due to the following CSS (related to icons), the text you want to style get also `font-family: "Material-Design-Icons";` applied, instead of Roboto. Which is annoying especially when you just want to color "normal" text and not icons.

``` less
[class^="mdi-"],
[class*=" mdi-"] {
  font-family: "Material-Design-Icons";
  speak: none;
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-transform: none;
  line-height: 1;
  /* Better Font Rendering =========== */
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```

Could you please allow text coloring by adding non mdi prefixed class, or any other solution? 
Thank you.
