### ISSUE TITLE
Add Less color variables in Meteor plugin

### ISSUE THREAD

**Issue by mbabauer** [mdbootstrap/mdb-ui-kit#453]
Would it be possible to have the Material color pallet represented with Less variables?  For instance, I'd like to do something like:

``` less
.div-title {
  background-color: @blue-grey;
  color: @white;
}

.div-body {
  background-color: @indigo-200;
  color: @black;
}
```

As a bonus, it would be nice if there were base classes with the Material colors setup that already have the `background-color` and corresponding `color` values set so we could do something like:

``` less
.my-div {
  &:extend(.deep-orange-600);
  padding: 15px;
}
```

and we would end up with

``` less
.my-div {
  background-color: #F4511E;
  color: #FFFFFF;
  padding: 15px;
}
```

If this already exists, my apologies.  I did look around for it, but didn't see anything like this.
