### ISSUE TITLE
need a way to skip checkbox initial animation

### ISSUE THREAD

**Issue by cncolder** [mdbootstrap/mdb-ui-kit#48]
currently. there are two key-animate defined on checkbox. normal and checked.
the animation will show at page load.
if i put checkbox in tabs content of bootstrap.
the animation will play every time when i switch tabs.

**Comment by cncolder** [comment]
a jsfiddle here http://jsfiddle.net/colder/6bqkz9tz/

**Comment by FezVrasta** [comment]
thanks, the current checkboxes and radio implementation is the best way I can think without have to use javascript for the animations...

If someone has some idea please share it

**Comment by npirotte** [comment]
You sould use transitions instead on animations. This is a little more tricky an less flexible bug i think there is a way to deal with that

**Comment by FezVrasta** [comment]
the first attempt was with transitions... I had troubles with them and was needed some JS to make everything works nicely.

**Comment by FezVrasta** [comment]
These are the two CSS animations used:

https://github.com/FezVrasta/bootstrap-material-design/blob/master/less/checkboxes.less#L88-L161

I can't see any way to convert them to simple CSS transitions...

**Comment by cncolder** [comment]
The only way i can think of:

``` less
input[type=checkbox]:not(:hover) {
  &, &:checked, &:not(:checked) {
    ~ .check {
       &:before, &:after {
         animation-duration: 1ms;
       }
     }
  }
}
```

not perfect. checkbox flickr at all. and have a strange ripple when hover.

http://jsfiddle.net/colder/6bqkz9tz/1/
