### ISSUE TITLE
CSS issue for Floating action buttons with caracter or glyphicon

### ISSUE THREAD

**Issue by overclokk** [mdbootstrap/mdb-ui-kit#498]
Hi, I have made some test with floating action buttons and I have found some issue with caracter or glyphicon inside button, here is a link http://www.codeply.com/go/P3xZTxerI6.

To solve this I have written a little bit of CSS

``` css
.btn.btn-fab{
    line-height: 1;
}
.btn-fab .glyphicon {
    font-size: 23px;
    left: 1.5px;
    top: 2px;
}
```

Font-size and line-height because glyphicon was bigger than MD icons
Left and top are for center the glyphicon but It works only for some icons, see the link before for other example.
