### ISSUE TITLE
Update Table Style to match new spec

### ISSUE THREAD

**Issue by GradyD** [mdbootstrap/mdb-ui-kit#555]
https://www.google.com/design/spec/components/data-tables.html#data-tables-tables-within-cards

Tag this as a feature/todo.

Thanks :+1:

**Comment by FezVrasta** [comment]
Here some LESS I've written. I had no time to implement it in the repo yet.

``` less
table {
  width: 100%;
  font-size: 12px;
  thead th {
    color: rgba(0, 0, 0, 0.46);
    font-weight: 400;
  }
  td, th {
    padding: 10px 15px;
    border-bottom: 1px solid #E0E0E0; 
  }
  tbody tr:hover {
    background-color: #EEEEEE;
  }
}
```
