### ISSUE TITLE
Table implementation

### ISSUE THREAD

**Issue by xingrz** [mdbootstrap/mdb-ui-kit#618]
According to: https://www.google.com/design/spec/components/data-tables.html

Rows of a table should be higher
#### Column headers
- size: 12px
- weight: medium
- color: 54% black
- height: 56px
#### Table content
- size: 13px
- weight: normal
- color: 87% black
- height: 48px

**Comment by rosskevin** [comment]
From Fez in duplicate #555 

Here some LESS I've written. I had no time to implement it in the repo yet.

``` less
table {
  width: 100%;
  font-size: 12px;
  thead th {
    color: rgba(0, 0, 0, 0.46);
    font-weight: 400;
  }
  td, th {
    padding: 10px 15px;
    border-bottom: 1px solid #E0E0E0; 
  }
  tbody tr:hover {
    background-color: #EEEEEE;
  }
}
```
