### ISSUE TITLE
Problem with autofill of Chrome

### ISSUE THREAD

**Issue by ferran294** [mdbootstrap/mdb-ui-kit#661]
I'm having problems with the **autofill** of Google **Chrome**, it changes the box of the input overriding the Bootstrap CSS. I have found solutions to override the autofill but it doesn't works applying the Bootstrap style. Someone has the solution to this? 

``` html


    <div class="row-fluid">
    <div class="form-group form-group-material-light-blue">
        <div class="col-lg-12">
            <input class="form-control" id="email" placeholder="Email" type="email" name="email"  required>
         </div>
    </div>
   </div>
```

This is the image example of the autofill problem:
![inputproblema](https://cloud.githubusercontent.com/assets/6933023/9056327/a21f8b9a-3a92-11e5-9750-77b8610741c3.png)

This is my partial solution to the problem but it would be better if the style was like the Bootstrap input, another solution would be disabling the autocomplete but I wouldn't like to do this:

``` css
input:-webkit-autofill {
    -webkit-box-shadow:0 0 0 50px white inset;
    -webkit-text-fill-color: #333;
}

input:-webkit-autofill:focus {
    -webkit-box-shadow: /*your box-shadow*/,0 0 0 50px white inset;
    -webkit-text-fill-color: #333;
}

```
