### ISSUE TITLE
Incorrect sass variable for links

### ISSUE THREAD

**Issue by tahq69** [mdbootstrap/mdb-ui-kit#782]
I revrite default bootstrap variable $link-color witch should owervrite only link colors, but in material design used $brand-primary color... it is incorrect for bootstrap

File: _core.scss line 33

``` scss
a, a:hover, a:focus {
  color: $brand-primary;

  & .material-icons {
    vertical-align: middle;
  }
}
```

Should be:

``` scss
a, a:hover, a:focus {
  color: $link-color;

  & .material-icons {
    vertical-align: middle;
  }
}
```

Same should be used in less files too...
By default, from less:

``` less
//** Global textual link color.
@link-color:            @brand-primary;
//** Link hover color set via `darken()` function.
@link-hover-color:      darken(@link-color, 15%);
//** Link hover decoration.
@link-hover-decoration: underline;
```
