### ISSUE TITLE
Regression on master - No ripple effect without form-group for checkbox and radio

### ISSUE THREAD

**Issue by tilwinjoy** [mdbootstrap/mdb-ui-kit#980]
Hi,

The  ripple effect is not working without `.form-group` for checkbox and radio.
I'm using chrome on Ubuntu machine.  (I don't think it's platform/browser specific issue since
the official demos for [checkbox](http://fezvrasta.github.io/bootstrap-material-design/#checkbox) and [radio](http://fezvrasta.github.io/bootstrap-material-design/#radio-button and) has ripple effect inside and outside `.form-group` on the same machine and browser).

[Outsitde form-group test case](http://codepen.io/anon/pen/Yqvvxx) - doesn't work (different than sample site)
[Inside form-group test case](http://codepen.io/anon/pen/JXZZOb) - works

**Comment by rosskevin** [comment]
Perhaps you should start with our template? 

https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md#tldr-create-a-test-case-using-this-codepen-template-when-submitting-an-issue

**Comment by tilwinjoy** [comment]
@rosskevin  updated with the template. The issue still seems to be there...

**Comment by rosskevin** [comment]
Curious, are you using a bower/npm release or `master`? (codpen points to `master`, so it may be a recent regression)

**Comment by tilwinjoy** [comment]
@rosskevin In the project I'm using bower couldn't make it work. That's why I tried to make it work with   minimal code in the jsfiddle I shared earlier. The codepen points to latest code as you said. Wondering how it works in the git hub demo page... it's points to `dist/css/bootstrap-material-design.css` and `dist/js/material.js` any idea which version they are? I checked the file but the version is not there...

**Comment by rosskevin** [comment]
Demo site is using the `gh-pages` branch, which is the last released version `0.5.9`.  You can pull from the tag: https://github.com/FezVrasta/bootstrap-material-design/releases

That confirms this as a regression.

**Comment by niravpatel9898** [comment]
@tilwinjoy Ctrf + F the below line in bootstrap-material-design.css:

`.checkbox input[type=checkbox]:checked + .checkbox-material:before`

change its css to the one given below, just give it a shot

```
.checkbox input[type=checkbox]:checked + .checkbox-material:before {
  -webkit-animation: rippleOn 500ms;
       -o-animation: rippleOn 500ms;
          animation: rippleOn 500ms;
}
```

**Comment by rosskevin** [comment]
@tilwinjoy I committed a `grunt dist` so the test cases above are using your last pull.  I was just curious if it changed anything regarding ripple but it didn't.  I'm a novice on animations.

@FezVrasta can you take a quick look at the test cases at the top?  The `dist` is up-to-date.

**Comment by FezVrasta** [comment]
I think I'm using `form-group` as wrapper for the `radio/toggle` and its JS added `ripple`. without it, the ripple element is not properly placed...

**Comment by tilwinjoy** [comment]
@rosskevin I believe it has to do with the removal of `forwards` property and duration from the animations (_they were present in the working version_). I'll look into it.

**Comment by tilwinjoy** [comment]
@rosskevin  The issue occurred due to the below changes, reverting it adds the animation back - [updated testcase](http://codepen.io/anon/pen/PNdayO)

However it looks like this changes were made so that the animation doesn't play on page load. In that case I'll look into an alternative solution (Maybe will end up controlling the animation on click via js?).

### checkbox

duration and fill-mode `0.3s forwards` removed from

``` css
 .check:before {
      ...
      animation: checkbox-off 0.3s forwards;
    }
```

duration `500ms;`removed from

``` css
    & + .checkbox-material:before {
        animation: rippleOn 500ms;
      }
```

and 

``` css
&:not(:checked) {
      & + .checkbox-material:before {
        animation: rippleOff 500ms;
      }
```

in favour of 

``` css
// Prevent checkbox animation and ripple effect on page load
.is-focused {
  .checkbox {
    .checkbox-material {
      .check:before {
        animation: checkbox-off @mdb-checkbox-animation-check forwards;
      }
    }
    input[type=checkbox] {
      &:checked {
        & + .checkbox-material:before {
          animation: rippleOn @mdb-checkbox-animation-ripple;
        }
      }
      &:not(:checked) {
        & + .checkbox-material:before {
          animation: rippleOff @mdb-checkbox-animation-ripple;
        }
      }
    }
  }
}
```

### radio:

duration `500ms` removed from

``` css
input[type=radio]:checked ~ .check:after {
      animation: rippleOn 500ms;
    }
```

In favor of 

``` css
// Prevent ripple effect on page load
.is-focused {
  .radio {
    input[type=radio]:checked ~ .check:after {
      animation: rippleOn 500ms;
    }
  }
}
```
