### ISSUE TITLE
v3 tabs implementation

### ISSUE THREAD

**Issue by derwok** [mdbootstrap/mdb-ui-kit#987]
#### Test Case

See official bootstrap-material docs here (search for "Tabs"). All items look the same, though they have classes applied like "active" or "disabled":

http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html

![tabs official](https://cloud.githubusercontent.com/assets/4393698/14942571/c5492dde-0fc0-11e6-8c95-38dcb3f9a6fe.png)
#### Summary

The current "nav-tabs" implementation seems to make no difference, if an item is active / non-active or disabled. Try it out on the above official "bootstrap-elements" page.

In the current V3 plain bootstrap our own menu looks like this (after clicking on "Open Topics"):
![tabs_bootstrap](https://cloud.githubusercontent.com/assets/4393698/14942573/c549543a-0fc0-11e6-802f-f5aeaecf7fc2.png)

with current V3 bootstrap-material-design applied the same menu looks like this:
![tabs material](https://cloud.githubusercontent.com/assets/4393698/14942572/c5494f26-0fc0-11e6-903d-5dcf38e93cf3.png)
(Note: I clicked on "Open Topics" so that item gets the "active" class attached).
#### Expected result

It would be great if the "active" item is highlighted in some way.
And if a disabled item is low-lighted in some way.

**Comment by rosskevin** [comment]
Agreed, I'm not sure if it was ever implemented or not.  These are implemented (at least from what I remember) in V4:
http://rosskevin.github.io/bootstrap-material-design/components/navs/#tabs

Here is the spec:
https://www.google.com/design/spec/components/tabs.html#tabs-usage

I welcome a PR that ports it back to v3, only the `.less` files need to be altered, the sass files are generated.

**Comment by derwok** [comment]
Unfortunately I'm not into LESS (only a littel CSS), so I keep my fingers crossed someone jumps in to help? Thanks in advance for taking care...  ;-)

**Comment by derwok** [comment]
Meanwhile, as a temporary workaround I use this:

``` css
/* highlight active nav-tabs item */
ul.nav-tabs {
    background-color: rgba(255, 255, 255, 0.0);
    border-bottom: .333rem solid transparent;
}
ul.nav-tabs li.active {
    border-bottom: .333rem solid teal;
    color: grey;
}
ul.nav-tabs li a,
ul.nav-tabs li a:focus
{
    color: grey !important;
}
ul.nav-tabs li a:hover {
    color: black !important;
}
```

Which renders like so:
![material-tabs_workaround](https://cloud.githubusercontent.com/assets/4393698/15006307/b3872036-11cf-11e6-9f4a-88aaefe95c97.png)
