### ISSUE TITLE
sprockets support

### ISSUE THREAD

**Issue by bcm** [mdbootstrap/mdb-ui-kit#99]
I'd like to use this theme in combination with a rails/sprockets application. any thoughts on supporting sprockets in the way that bootstrap-sass does?

see https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/_bootstrap-sprockets.scss and https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_glyphicons.scss#L17 for a quick sense of how that project supports sprockets' digested asset urls.

**Comment by FezVrasta** [comment]
I've not experience with sass, ping @shockwork

**Comment by TransitoryBliss** [comment]
I will look into it :)

**Comment by FezVrasta** [comment]
thanks man :)

**Comment by TransitoryBliss** [comment]
@FezVrasta I'm on the chat btw!

**Comment by FezVrasta** [comment]
Sorry I've a movie-popcorn evening with my gf and my cat tonight :P

**Comment by TransitoryBliss** [comment]
Aight mate, you deserve it :D Have a good one!

**Comment by bcm** [comment]
thanks y'all!

fwiw, I have a local hack that looks like this:

``` scss
@font-face {
    font-family: "Material-Design";
    src: asset-url("Material-Design.eot?2u7a7w");
    src: asset-url("Material-Design.eot?#iefix2u7a7w") format("embedded-opentype"),
         asset-url("Material-Design.woff?2u7a7w") format("woff"),
         asset-url("Material-Design.ttf?2u7a7w") format("truetype"),
         asset-url("Material-Design.svg?2u7a7w#Material-Design") format("svg");
    font-weight: normal;
    font-style: normal;
}
```

these asset urls are specified relative to `vendor/assets/bower_components/bootstrap-material-design/fonts`, which I've added to my sprockets asset paths.

**Comment by TransitoryBliss** [comment]
I've looked into sprockets but I'm not really sure that we gain enough by adding it. Why do you feel like Sprockets would be needed? We'd like to keep the repository at it's core, adding support for all kinds of asset pipelines and frameworks clutters it. With that said - if there's reason enough I will add it. So what's your pitch? :sunglasses:

**Comment by bcm** [comment]
well, I need to do _something_ in order to use this library with my Rails application. because of the way Rails' asset pipeline works (compiling assets and placing the output in a different filesystem location with a different filename then the ones in your source directory), you can't reference one asset from another asset using a hardcoded url.

let me try to make the point with a concrete example.

in my application, material.css lives within the application root at `vendor/assets/bower_components/bootstrap-material-design/dist/css/material.css`. my application is configured to search for assets in, among other filesystem locations, `vendor/assets/bower_components/bootstrap-material-design/dist`.

material.css includes the following code - note the relative urls referencing various font resources:

``` css
@font-face {
  src: url("../fonts/Material-Design.eot?2u7a7w");
  src: url("../fonts/Material-Design.eot?#iefix2u7a7w") format("embedded-opentype"), url("../fonts/Material-Design.woff?2u7a7w") format("woff"), url("../fonts/Material-Design.ttf?2u7a7w") format("truetype"), url("../fonts/Material-Design.svg?2u7a7w#Material-Design") format("svg");
}
```

when I'm running my application in my development environment, I can add a link tag to an html page that refers to the stylesheet at `/css/material.css`. in this context, the embedded font urls resolve to eg `/fonts/Material-Design.eot` which **in my development environment** refers to an existing resource.

however, when I deploy my application to production, the Rails asset pipeline (ie Sprockets) processes this css file, running it through a minifier, writing the output to some arbitrary location in the `tmp` dir within my application root, renaming the file `material.css-<digest>`. a similar process occurs for the font resources. the application has logic to map urls of the form `/assets/*` to the location in the `tmp` dir.

given this, neither `/css/materials.css` `/fonts/Material-Design.eot` resolves to a resource in my production environment; instead I have to use `/assets/material.css-<digest>` and `/assets/Material-Design.eot-<digest>`. in my html file I have a special Rails helper function that writes out a link tag with a url that points to the "compiled" version of the css file available within `/assets`. but now the hardcoded font urls within the css file don't actually resolve to anything in the production environment.

this is why Sprockets provides the `asset-url` scss directive that I referenced in my earlier comment; during the compilation process it replaces the directive with the url to the "compiled" version of the asset within `/assets`.

in the original post I referenced bootstrap-sass's way of solving this problem, which is to provide a scss function that in a Sprockets application uses the sprockets helper to deal with urls correctly in all application environments, and in other applications just falls back to the built in css `url` mechanism. it's nicely modularized so that the core just provides an "interface" and a default implementation, and a separate scss file provides a Sprockets implementation; Sprockets applications can include that file to turn on Sprockets support while other applications can just ignore the issue altogether.

I'm happy to put some time into a patch if you all are willing to accept the notion that hardcoding asset urls within scss and less files is problematic in the scenario I've described and that we can solve the problem pretty simply without adding too much complexity.
